# Generated by Django 3.0.5 on 2025-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finance_approved',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='lab_approved',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='pc_approved',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='technical_approved',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='technical_fin_approved',
            field=models.CharField(default='No', max_length=40),
        ),
    ]
