# Generated by Django 3.0.5 on 2025-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20250120_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='vehicle_name',
            new_name='vehicle_reg',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_no',
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('major', 'major'), ('minor', 'minor'), ('routine service', 'routine service')], max_length=50),
        ),
    ]
