# Generated by Django 3.0.5 on 2025-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20250120_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finance',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='lab_manager',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='pc',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='technical',
            field=models.CharField(default='.', max_length=40),
        ),
    ]
