# Generated by Django 3.0.5 on 2025-01-20 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0012_auto_20250120_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='finance',
            field=models.CharField(choices=[('Macfarland Mware', 'Macfarland Mware'), ('Mcmillan Makayi', 'Mcmillan Makayi')], max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='pc',
            field=models.CharField(choices=[('Mavis Moyo', 'Mavis Moyo'), ('Lisben Maguwu', 'Lisben Maguwu'), ('Phillip Muzavazi', 'Phillip Muzavazi'), ('David Gatsi', 'David Gatsi'), ('Faustinas Tasara', 'Faustinas Tasara'), ('Nyasha Tsvangirai', 'Nyasha Tsvangirai'), ('Blessed Mudhumo', 'Blessed Mudhumo'), ('Edmore Mukaronda', 'Edmore Mukaronda')], max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='technical',
            field=models.CharField(choices=[('Agripa Mtambara', 'Agripa Mtambara')], max_length=40),
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
