# Generated by Django 3.0.5 on 2025-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_auto_20250120_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='finance',
            field=models.CharField(choices=[('Macfarland Mware', 'mmware'), ('Mcmillan Makayi', 'mmakayi')], max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='pc',
            field=models.CharField(choices=[('Mavis Moyo', 'mmoyo'), ('Lisben Maguwu', 'lmaguwu'), ('Phillip Muzavazi', 'pmuzavazi'), ('David Gatsi', 'dgatsi'), ('Faustinas Tasara', 'ftasara'), ('Nyasha Tsvangirai', 'ntsvangirai'), ('Blessed Mudhumo', 'bmudhumo'), ('Edmore Mukaronda', 'emukaronda')], max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='technical',
            field=models.CharField(choices=[('Agripa Mtambara', 'amtambara')], max_length=40),
        ),
    ]
