# Generated by Django 3.0.5 on 2025-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20250320_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
