# Generated by Django 3.0.5 on 2025-03-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_customer_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='finance',
            field=models.CharField(choices=[('mmware', 'mmware'), ('mmakayi', 'mmakayi')], max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='lab_manager',
            field=models.CharField(choices=[('manager1', 'manager1'), ('manager2', 'manager2'), ('manager3', 'manager3')], max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='pc',
            field=models.CharField(choices=[('mmoyo', 'mmoyo'), ('lmaguwu', 'lmaguwu'), ('pmuzavazi', 'pmuzavazi'), ('dgatsi', 'dgatsi'), ('ftasara', 'ftasara'), ('ntsvangirai', 'ntsvangirai'), ('bmudhumo', 'bmudhumo'), ('emukaronda', 'emukaronda')], max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='technical',
            field=models.CharField(choices=[('amtambara', 'amtambara')], max_length=40),
        ),
    ]
