# Generated by Django 3.0.5 on 2025-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_auto_20250321_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer1',
            field=models.CharField(default='', max_length=40),
        ),
    ]
