# Generated by Django 3.0.5 on 2025-05-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_request_customer1'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='job_open',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=1000)),
                ('quotation', models.CharField(max_length=500)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Request')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Mechanic')),
            ],
        ),
    ]
