# Generated by Django 3.0.5 on 2025-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_auto_20250522_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='job',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mechanic',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
