# Generated by Django 3.0.5 on 2025-06-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_auto_20250522_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.CharField(default='1', max_length=100)),
                ('job', models.CharField(default='1', max_length=100)),
                ('assessment', models.TextField(max_length=1000)),
                ('quotation', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
