# Generated by Django 3.0.5 on 2025-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0020_auto_20250620_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='subs',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
