# Generated by Django 3.0.5 on 2025-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_request_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='mechanic',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
