# Generated by Django 3.0.5 on 2025-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_auto_20250717_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='supplier_justification',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
