# Generated by Django 3.0.5 on 2025-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0023_request_supplier_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='assessement_id',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
