# Generated by Django 3.0.5 on 2025-07-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0024_request_assessement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reasons',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
