# Generated by Django 3.0.5 on 2025-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0025_request_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='dos',
            field=models.CharField(default='.', max_length=500),
        ),
        migrations.AddField(
            model_name='request',
            name='finance_approved_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='job_open_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='pc_approved_date',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='technical_approved_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='technical_fin_approved_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AlterField(
            model_name='request',
            name='technical',
            field=models.CharField(default='amtambara', max_length=40),
        ),
    ]
