# Generated by Django 3.0.5 on 2025-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0026_auto_20250720_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='supplier_accepted',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='supplier_accepted_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='supplier_done',
            field=models.CharField(default='No', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='supplier_done_date',
            field=models.CharField(default='.', max_length=40),
        ),
    ]
