# Generated by Django 3.0.5 on 2025-07-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0028_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cos',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='service',
            name='manager_approved',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='service',
            name='manager_approved_date',
            field=models.TextField(default='.'),
        ),
    ]
