# Generated by Django 3.0.5 on 2025-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0029_auto_20250721_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='invoice',
            field=models.TextField(default='.'),
        ),
    ]
