# Generated by Django 3.0.5 on 2025-07-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0030_service_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='next_service',
            field=models.TextField(default='0'),
        ),
    ]
