# Generated by Django 3.0.5 on 2025-07-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0031_service_next_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lab_manager',
            field=models.TextField(default='manager1'),
        ),
    ]
