# Generated by Django 3.0.5 on 2025-07-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0032_service_lab_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='POP',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='tech',
            field=models.TextField(default='amtambara'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_approved',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_approved_date',
            field=models.TextField(default='.'),
        ),
    ]
