# Generated by Django 3.0.5 on 2025-07-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0033_auto_20250723_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finance_rejected_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='lab_approved_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='lab_rejected_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='pc_rejected_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='supplier_rejected_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='technical_fin_rejected_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='technical_rejected_date',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.AddField(
            model_name='service',
            name='manager_rejected_date',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_rejected_date',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='request',
            name='pc_approved_date',
            field=models.CharField(default='.', max_length=40),
        ),
    ]
