# Generated by Django 3.0.5 on 2025-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0034_auto_20250724_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='POP_date',
            field=models.TextField(default='.'),
        ),
    ]
