# Generated by Django 3.0.5 on 2025-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0035_service_pop_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(max_length=20)),
                ('District', models.TextField()),
                ('Province', models.TextField()),
                ('status', models.TextField()),
                ('status_date', models.TextField()),
                ('next_service', models.TextField()),
                ('last_service', models.TextField()),
                ('last_service_details', models.TextField()),
                ('estimate_milage', models.TextField()),
            ],
        ),
    ]
