# Generated by Django 3.0.5 on 2025-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0036_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='yr_procured',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='status_date',
            field=models.TextField(default='.'),
        ),
    ]
