# Generated by Django 3.0.5 on 2025-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0037_auto_20250801_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='days_of_non_f',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='bike',
            name='reasons_for_non_f',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='request',
            name='date1',
            field=models.DateField(auto_now=True),
        ),
    ]
