<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-09-08 14:10
=======
# Generated by Django 3.0.5 on 2025-08-06 13:56
>>>>>>> d2ccc5b0df0b1f0dab117f256e46fd153c03cfcb

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0038_auto_20250804_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='age',
            field=models.TextField(default='.'),
        ),
    ]
