# Generated by Django 5.2.4 on 2025-09-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0038_auto_20250804_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='age',
            field=models.TextField(default='.'),
        ),
    ]
