# Generated by Django 3.0.5 on 2025-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0038_auto_20250804_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='age',
            field=models.TextField(default='.'),
        ),
    ]
