# Generated by Django 3.0.5 on 2025-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0039_bike_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='current_milage',
            field=models.TextField(default='0'),
        ),
    ]
