# Generated by Django 3.0.5 on 2025-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0040_service_current_milage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='next_service',
            new_name='next_service_major',
        ),
        migrations.AddField(
            model_name='service',
            name='next_service_minor',
            field=models.TextField(default='0'),
        ),
    ]
