# Generated by Django 3.0.5 on 2025-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0041_auto_20250807_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='last_service_date',
            field=models.TextField(default='.'),
        ),
    ]
