# Generated by Django 3.0.5 on 2025-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0042_bike_last_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='distance_traveled_since_last_service',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='service',
            name='CSS',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='CSS_date',
            field=models.TextField(default='.'),
        ),
    ]
