# Generated by Django 3.0.5 on 2025-09-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0043_auto_20250908_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date1',
            field=models.DateField(null=True),
        ),
    ]
